default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: pokedex_db
  user: postgres

development:
  <<: *default
  database: pokedex-api_development

test:
  <<: *default
  database: pokedex-api_test

production:
  <<: *default
  database: pokedex-api_production
  username: pokedex-api
  password: <%= ENV['POKEDEX-API_DATABASE_PASSWORD'] %>
